server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: azsxdcfv
    url: jdbc:postgresql://localhost:5432/fraud
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans